version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"

workflows:
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
